[mypy]
mypy_path = src/semana_1/dia_01_lunes/actividad_01, 
            src/semana_1/dia_02_martes/actividad_01, 
            src/semana_1/dia_02_martes/actividad_02, 
            src/semana_1/dia_03_miercoles/actividad_01,
            src/semana_1/dia_03_miercoles/actividad_02, 
            src/semana_1/dia_04_jueves/actividad_01, 
            src/semana_1/dia_05_viernes/uart_driver,
explicit_package_bases = True